# You can configure Blacklight from here.
#
#   Blacklight.configure(:environment) do |config| end
#
# :shared (or leave it blank) is used by all environments.
# You can override a shared key by using that key in a particular
# environment's configuration.
#
# If you have no configuration beyond :shared for an environment, you
# do not need to call configure() for that envirnoment.
#
# For specific environments:
#
#   Blacklight.configure(:test) {}
#   Blacklight.configure(:development) {}
#   Blacklight.configure(:production) {}
#

Blacklight.configure(:shared) do |config|

  # default params for the SolrDocument.search method
  SolrDocument.default_params[:search] = {
    :qt=>:search,
    :per_page => 10,
    :facets => {
      :fields => [
      ]
    }
  }

  # default params for the SolrDocument.find_by_id method
  SolrDocument.default_params[:find_by_id] = {:qt => :document}

  ##############################

  config[:default_qt] = "search"

  # solr field values given special treatment in the show (single result) view
  config[:show] = {
    :html_title => "id",
    :heading => "id",
    :display_type => "format_code"
  }

  # solr fld values given special treatment in the index (search results) view
  config[:index] = {
    :show_link => "id",
    :num_per_page => 10,
    :record_display_type => "format_code"
  }

  # solr fields that will be treated as facets by the blacklight application
  #   The ordering of the field names is the order of the display
  config[:facet] = {
    :field_names => [
      "BITPIX",
      "BLOCK",
      "COMMENT",
      "COORDSYS",
      "DATE-OBS",
      "DATEBLD",
      "DEC",
      "EQUINOX",
      "EXTEND",
      "FITSVER",
      "GBTMCVER",
      "INSTRUME",
      "LASTOFF",
      "LASTON",
      "NAXIS",
      "OBJECT",
      "OBSERVER",
      "OBSID",
      "OBSTYPE",
      "OOFDZ",
      "ORIGIN",
      "PROCNAME",
      "PROCSEQN",
      "PROCSIZE",
      "PROCTYPE",
      "PROJID",
      "PTSCALE",
      "RA",
      "RADESYS",
      "RESTFRQ",
      "SCAN",
      "SCANFILE",
      "SIMPLE",
      "SIMULATE",
      "SKYFREQ",
      "SUBMOTIN",
      "SUBNODLN",
      "SUBNUNIT",
      "SUBOFFSY",
      "SUBSTRTY",
      "SUBXT1",
      "SUBXT2",
      "SUBYT1",
      "SUBYT2",
      "SUBZT1",
      "SUBZT2",
      "SWSTATE",
      "SWTCHSIG",
      "TELESCOP",
      "TIMESYS",
      "VELDEF",
      "VELOCITY",
      "catalog_F1",
      "catalog_S1400",
      "catalog_S1_3",
      "catalog_S2",
      "catalog_S22235",
      "catalog_S3_5",
      "catalog_S6",
      "catalog_location",
      "catalog_source",
      "catalog_veldef",
      "catalog_velocity",
      "config_",
      "config_backend",
      "config_bandwidth",
      "config_beam",
      "config_deltafreq",
      "config_if3freq",
      "config_iftarget",
      "config_nchan",
      "config_noisecal",
      "config_nwin",
      "config_obstype",
      "config_pol",
      "config_polswitch",
      "config_receiver",
      "config_restfreq",
      "config_spect_crosspol",
      "config_spect_levels",
      "config_swfreq",
      "config_swmode",
      "config_swper",
      "config_swtype",
      "config_tint",
      "config_vdef",
      "config_vframe",
      "config_vhigh",
      "config_vlbi_phasecal",
      "config_vlow",
      "config_xfer",
    ],
    :labels => {
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "INSTRUME" => "INSTRUME",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "catalog_F1" => "catalog_F1",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S6" => "catalog_S6",
      "catalog_location" => "catalog_location",
      "catalog_source" => "catalog_source",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "config_" => "config_",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_beam" => "config_beam",
      "config_deltafreq" => "config_deltafreq",
      "config_if3freq" => "config_if3freq",
      "config_iftarget" => "config_iftarget",
      "config_nchan" => "config_nchan",
      "config_noisecal" => "config_noisecal",
      "config_nwin" => "config_nwin",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_xfer" => "config_xfer",
    }
  }

  # solr fields to be displayed in the index (search results) view
  #   The ordering of the field names is the order of the display
  config[:index_fields] = {
    :field_names => [
      "OBSERVER",
      "INSTRUME",
      "GBTMCVER",
      "FITSVER",
      "COORDSYS",
    ],
    :labels => {
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "INSTRUME" => "INSTRUME",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "catalog_F1" => "catalog_F1",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S6" => "catalog_S6",
      "catalog_location" => "catalog_location",
      "catalog_source" => "catalog_source",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "config_" => "config_",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_beam" => "config_beam",
      "config_deltafreq" => "config_deltafreq",
      "config_if3freq" => "config_if3freq",
      "config_iftarget" => "config_iftarget",
      "config_nchan" => "config_nchan",
      "config_noisecal" => "config_noisecal",
      "config_nwin" => "config_nwin",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_xfer" => "config_xfer",
    }
  }

  # solr fields to be displayed in the show (single result) view
  #   The ordering of the field names is the order of the display
  config[:show_fields] = {
    :field_names => [
      "BITPIX",
      "BLOCK",
      "COMMENT",
      "COORDSYS",
      "DATE-OBS",
      "DATEBLD",
      "DEC",
      "EQUINOX",
      "EXTEND",
      "FITSVER",
      "GBTMCVER",
      "INSTRUME",
      "LASTOFF",
      "LASTON",
      "NAXIS",
      "OBJECT",
      "OBSERVER",
      "OBSID",
      "OBSTYPE",
      "OOFDZ",
      "ORIGIN",
      "PROCNAME",
      "PROCSEQN",
      "PROCSIZE",
      "PROCTYPE",
      "PROJID",
      "PTSCALE",
      "RA",
      "RADESYS",
      "RESTFRQ",
      "SCAN",
      "SCANFILE",
      "SIMPLE",
      "SIMULATE",
      "SKYFREQ",
      "SUBMOTIN",
      "SUBNODLN",
      "SUBNUNIT",
      "SUBOFFSY",
      "SUBSTRTY",
      "SUBXT1",
      "SUBXT2",
      "SUBYT1",
      "SUBYT2",
      "SUBZT1",
      "SUBZT2",
      "SWSTATE",
      "SWTCHSIG",
      "TELESCOP",
      "TIMESYS",
      "VELDEF",
      "VELOCITY",
      "catalog_F1",
      "catalog_S1400",
      "catalog_S1_3",
      "catalog_S2",
      "catalog_S22235",
      "catalog_S3_5",
      "catalog_S6",
      "catalog_location",
      "catalog_source",
      "catalog_veldef",
      "catalog_velocity",
      "config_",
      "config_backend",
      "config_bandwidth",
      "config_beam",
      "config_deltafreq",
      "config_if3freq",
      "config_iftarget",
      "config_nchan",
      "config_noisecal",
      "config_nwin",
      "config_obstype",
      "config_pol",
      "config_polswitch",
      "config_receiver",
      "config_restfreq",
      "config_spect_crosspol",
      "config_spect_levels",
      "config_swfreq",
      "config_swmode",
      "config_swper",
      "config_swtype",
      "config_tint",
      "config_vdef",
      "config_vframe",
      "config_vhigh",
      "config_vlbi_phasecal",
      "config_vlow",
      "config_xfer",
    ],
    :labels => {
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "INSTRUME" => "INSTRUME",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "catalog_F1" => "catalog_F1",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S6" => "catalog_S6",
      "catalog_location" => "catalog_location",
      "catalog_source" => "catalog_source",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "config_" => "config_",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_beam" => "config_beam",
      "config_deltafreq" => "config_deltafreq",
      "config_if3freq" => "config_if3freq",
      "config_iftarget" => "config_iftarget",
      "config_nchan" => "config_nchan",
      "config_noisecal" => "config_noisecal",
      "config_nwin" => "config_nwin",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_xfer" => "config_xfer",
    }
  }

  # "fielded" search select (pulldown)
  # label in pulldown is followed by the name of a SOLR request handler as
  # defined in solr/conf/solrconfig.xml
  config[:search_fields] ||= []
  config[:search_fields] << ['All Fields', 'search']
  # config[:search_fields] << ['Title', 'title_search']

  # "sort results by" select (pulldown)
  # label in pulldown is followed by the name of the SOLR field to sort by and
  # whether the sort is ascending or descending (it must be asc or desc
  # except in the relevancy case).
  # label is key, solr field is value
  config[:sort_fields] ||= []
  config[:sort_fields] << ['relevance', 'score desc, title_sort asc']

  # If there are more than this many search results, no spelling ("did you
  # mean") suggestion is offered.
  config[:spell_max] = 5
end

