# You can configure Blacklight from here.
#
#   Blacklight.configure(:environment) do |config| end
#
# :shared (or leave it blank) is used by all environments.
# You can override a shared key by using that key in a particular
# environment's configuration.
#
# If you have no configuration beyond :shared for an environment, you
# do not need to call configure() for that envirnoment.
#
# For specific environments:
#
#   Blacklight.configure(:test) {}
#   Blacklight.configure(:development) {}
#   Blacklight.configure(:production) {}
#

Blacklight.configure(:shared) do |config|

  # default params for the SolrDocument.search method
  SolrDocument.default_params[:search] = {
    :qt=>:search,
    :per_page => 10,
    :facets => {
      :fields => [
      ]
    }
  }

  # default params for the SolrDocument.find_by_id method
  SolrDocument.default_params[:find_by_id] = {:qt => :document}

  ##############################

  config[:default_qt] = "search"

  # solr field values given special treatment in the show (single result) view
  config[:show] = {
    :html_title => "id",
    :heading => "id",
    :display_type => "format_code"
  }

  # solr fld values given special treatment in the index (search results) view
  config[:index] = {
    :show_link => "id",
    :num_per_page => 10,
    :record_display_type => "format_code"
  }

  # solr fields that will be treated as facets by the blacklight application
  #   The ordering of the field names is the order of the display
  config[:facet] = {
    :field_names => [
      "keys",
      "CALTAG",
      "COORDSYS",
      "EQUINOX",
      "FITSVER",
      "GBTMCVER",
      "INSTRUME",
      "NAXIS",
      "OBSTYPE",
      "ORIGIN",
      "PROCNAME",
      "PROCTYPE",
      "PTSCALE",
      "RADESYS",
      "SIMPLE",
      "SIMULATE",
      "SUBMOTIN",
      "SUBNUNIT",
      "SWSTATE",
      "SWTCHSIG",
      "TELESCOP",
      "TIMESYS",
      "VELDEF",
      "catalog_veldef",
      "config_backend",
      "config_bandwidth",
      "config_beam",
      "config_nchan",
      "config_noisecal",
      "config_notchfilter",
      "config_nwin",
      "config_obstype",
      "config_pol",
      "config_polswitch",
      "config_receiver",
      "config_swmode",
      "config_swtype",
      "config_vdef",
      "config_vframe",
      "config_vlbi_phasecal",
      "config_xfer",
    ],
    :labels => {
      "keys" => "keys",
      "AZ" => "AZ",
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "CALTAG" => "CALTAG",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "DIODE" => "DIODE",
      "EL" => "EL",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "GLAT" => "GLAT",
      "GLON" => "GLON",
      "HA" => "HA",
      "HALFPOW" => "HALFPOW",
      "INSTRUME" => "INSTRUME",
      "KADRIFT" => "KADRIFT",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "LEDTEST" => "LEDTEST",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTAG" => "OBSTAG",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SRCCNT" => "SRCCNT",
      "SRCTYPE" => "SRCTYPE",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "TRADHOLO" => "TRADHOLO",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "ZERNSFC" => "ZERNSFC",
      "catalog_AKA" => "catalog_AKA",
      "catalog_BMAX" => "catalog_BMAX",
      "catalog_BMIN" => "catalog_BMIN",
      "catalog_DejaVu" => "catalog_DejaVu",
      "catalog_F1" => "catalog_F1",
      "catalog_FILE" => "catalog_FILE",
      "catalog_INTENSITY" => "catalog_INTENSITY",
      "catalog_LINE" => "catalog_LINE",
      "catalog_Line" => "catalog_Line",
      "catalog_NAME" => "catalog_NAME",
      "catalog_NEDname" => "catalog_NEDname",
      "catalog_NOBSQ" => "catalog_NOBSQ",
      "catalog_NOBSX" => "catalog_NOBSX",
      "catalog_NVSS" => "catalog_NVSS",
      "catalog_OFFSET" => "catalog_OFFSET",
      "catalog_P" => "catalog_P",
      "catalog_RESTFREQ" => "catalog_RESTFREQ",
      "catalog_Rgal" => "catalog_Rgal",
      "catalog_S0_7" => "catalog_S0_7",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S15" => "catalog_S15",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S20" => "catalog_S20",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_3" => "catalog_S3_3",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S400" => "catalog_S400",
      "catalog_S6" => "catalog_S6",
      "catalog_SZMAX" => "catalog_SZMAX",
      "catalog_SZMIN" => "catalog_SZMIN",
      "catalog_TCJ" => "catalog_TCJ",
      "catalog_USERADVEL" => "catalog_USERADVEL",
      "catalog_VEL" => "catalog_VEL",
      "catalog_VELOCITY" => "catalog_VELOCITY",
      "catalog_Velocity" => "catalog_Velocity",
      "catalog_alias" => "catalog_alias",
      "catalog_angsize" => "catalog_angsize",
      "catalog_b" => "catalog_b",
      "catalog_binary" => "catalog_binary",
      "catalog_bname" => "catalog_bname",
      "catalog_bsc_efact" => "catalog_bsc_efact",
      "catalog_bsize" => "catalog_bsize",
      "catalog_color" => "catalog_color",
      "catalog_coordinates" => "catalog_coordinates",
      "catalog_coordname" => "catalog_coordname",
      "catalog_dec_deg" => "catalog_dec_deg",
      "catalog_decoffset" => "catalog_decoffset",
      "catalog_decsize" => "catalog_decsize",
      "catalog_dm" => "catalog_dm",
      "catalog_e95_amin" => "catalog_e95_amin",
      "catalog_found_by" => "catalog_found_by",
      "catalog_itime" => "catalog_itime",
      "catalog_jname" => "catalog_jname",
      "catalog_l" => "catalog_l",
      "catalog_location" => "catalog_location",
      "catalog_lsize" => "catalog_lsize",
      "catalog_myraoff" => "catalog_myraoff",
      "catalog_offDec" => "catalog_offDec",
      "catalog_parfile" => "catalog_parfile",
      "catalog_pk" => "catalog_pk",
      "catalog_ra_deg" => "catalog_ra_deg",
      "catalog_region" => "catalog_region",
      "catalog_restframe" => "catalog_restframe",
      "catalog_restfreq" => "catalog_restfreq",
      "catalog_source" => "catalog_source",
      "catalog_start_lst" => "catalog_start_lst",
      "catalog_status" => "catalog_status",
      "catalog_t" => "catalog_t",
      "catalog_vel" => "catalog_vel",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "catalog_velocitydefinition" => "catalog_velocitydefinition",
      "catalog_z" => "catalog_z",
      "config_" => "config_",
      "config_CCO" => "config_CCO",
      "config_CCS" => "config_CCS",
      "config_H2O" => "config_H2O",
      "config_HC11N_23" => "config_HC11N_23",
      "config_HC11N_24" => "config_HC11N_24",
      "config_HC11N_25" => "config_HC11N_25",
      "config_HC11N_26" => "config_HC11N_26",
      "config_HC11N_27" => "config_HC11N_27",
      "config_HC11N_28" => "config_HC11N_28",
      "config_HC11N_29" => "config_HC11N_29",
      "config_HC11N_37" => "config_HC11N_37",
      "config_HC11N_38" => "config_HC11N_38",
      "config_HC11N_39" => "config_HC11N_39",
      "config_HC11and7N" => "config_HC11and7N",
      "config_HC13N_59" => "config_HC13N_59",
      "config_HC13N_60" => "config_HC13N_60",
      "config_HC13N_61" => "config_HC13N_61",
      "config_HC13N_62" => "config_HC13N_62",
      "config_HC13N_63" => "config_HC13N_63",
      "config_HC3N_0" => "config_HC3N_0",
      "config_HC5N_2" => "config_HC5N_2",
      "config_HC7NJ19" => "config_HC7NJ19",
      "config_HC7N_11" => "config_HC7N_11",
      "config_HC7N_7" => "config_HC7N_7",
      "config_HC7N_8" => "config_HC7N_8",
      "config_HC9NJ37" => "config_HC9NJ37",
      "config_HC9NJ38" => "config_HC9NJ38",
      "config_HC9N_13" => "config_HC9N_13",
      "config_HC9N_14" => "config_HC9N_14",
      "config_HC9N_15" => "config_HC9N_15",
      "config_HC9N_16" => "config_HC9N_16",
      "config_HC9N_22" => "config_HC9N_22",
      "config_HDO" => "config_HDO",
      "config_NH3J42" => "config_NH3J42",
      "config_NH3J54" => "config_NH3J54",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_bcpm_ch_bw" => "config_bcpm_ch_bw",
      "config_bcpm_hardware" => "config_bcpm_hardware",
      "config_bcpm_sample_time" => "config_bcpm_sample_time",
      "config_bcpm_source_name" => "config_bcpm_source_name",
      "config_bcpm_submanager" => "config_bcpm_submanager",
      "config_bcpm_sum_pol" => "config_bcpm_sum_pol",
      "config_beam" => "config_beam",
      "config_beamswitch" => "config_beamswitch",
      "config_cal" => "config_cal",
      "config_ccb_XL_on_integs" => "config_ccb_XL_on_integs",
      "config_ccb_YR_on_integs" => "config_ccb_YR_on_integs",
      "config_ccb_both_on_integs" => "config_ccb_both_on_integs",
      "config_ccb_bswfreq" => "config_ccb_bswfreq",
      "config_ccb_cal_off_integs" => "config_ccb_cal_off_integs",
      "config_deltafreq" => "config_deltafreq",
      "config_guppi_datadisk" => "config_guppi_datadisk",
      "config_guppi_fold_bins" => "config_guppi_fold_bins",
      "config_guppi_fold_dumptime" => "config_guppi_fold_dumptime",
      "config_guppi_fold_parfile" => "config_guppi_fold_parfile",
      "config_guppi_numchan" => "config_guppi_numchan",
      "config_guppi_obsmode" => "config_guppi_obsmode",
      "config_guppi_outbits" => "config_guppi_outbits",
      "config_guppi_parfile" => "config_guppi_parfile",
      "config_guppi_polnmode" => "config_guppi_polnmode",
      "config_guppi_scale" => "config_guppi_scale",
      "config_holo_refatten" => "config_holo_refatten",
      "config_holo_reqinteg" => "config_holo_reqinteg",
      "config_holo_testatten" => "config_holo_testatten",
      "config_if3freq" => "config_if3freq",
      "config_ifbw" => "config_ifbw",
      "config_iftarget" => "config_iftarget",
      "config_lo2freq" => "config_lo2freq",
      "config_mustang_defaultdac" => "config_mustang_defaultdac",
      "config_mustang_init" => "config_mustang_init",
      "config_mustang_lsync" => "config_mustang_lsync",
      "config_mustang_lutstart" => "config_mustang_lutstart",
      "config_mustang_nsamp" => "config_mustang_nsamp",
      "config_mustang_nstep" => "config_mustang_nstep",
      "config_mustang_settle" => "config_mustang_settle",
      "config_mustang_tuning" => "config_mustang_tuning",
      "config_nchan" => "config_nchan",
      "config_nfeeds" => "config_nfeeds",
      "config_noisecal" => "config_noisecal",
      "config_notchfilter" => "config_notchfilter",
      "config_nwin" => "config_nwin",
      "config_obsmode" => "config_obsmode",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polarization" => "config_polarization",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_smode" => "config_smode",
      "config_sp_mode" => "config_sp_mode",
      "config_sp_polyco" => "config_sp_polyco",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_spect_numbanks" => "config_spect_numbanks",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_vnoisecal" => "config_vnoisecal",
      "config_xfer" => "config_xfer",
    }
  }

  # solr fields to be displayed in the index (search results) view
  #   The ordering of the field names is the order of the display
  config[:index_fields] = {
    :field_names => [
      "OBSERVER",
      "INSTRUME",
      "GBTMCVER",
      "FITSVER",
      "COORDSYS",
    ],
    :labels => {
      "keys" => "keys",
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "INSTRUME" => "INSTRUME",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "catalog_F1" => "catalog_F1",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S6" => "catalog_S6",
      "catalog_location" => "catalog_location",
      "catalog_source" => "catalog_source",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "config_" => "config_",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_beam" => "config_beam",
      "config_deltafreq" => "config_deltafreq",
      "config_if3freq" => "config_if3freq",
      "config_iftarget" => "config_iftarget",
      "config_nchan" => "config_nchan",
      "config_noisecal" => "config_noisecal",
      "config_nwin" => "config_nwin",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_xfer" => "config_xfer",
    }
  }

  # solr fields to be displayed in the show (single result) view
  #   The ordering of the field names is the order of the display
  config[:show_fields] = {
    :field_names => [
      "AZ",
      "BITPIX",
      "BLOCK",
      "CALTAG",
      "COMMENT",
      "COORDSYS",
      "DATE-OBS",
      "DATEBLD",
      "DEC",
      "DIODE",
      "EL",
      "EQUINOX",
      "EXTEND",
      "FITSVER",
      "GBTMCVER",
      "GLAT",
      "GLON",
      "HA",
      "HALFPOW",
      "INSTRUME",
      "KADRIFT",
      "LASTOFF",
      "LASTON",
      "LEDTEST",
      "NAXIS",
      "OBJECT",
      "OBSERVER",
      "OBSID",
      "OBSTAG",
      "OBSTYPE",
      "OOFDZ",
      "ORIGIN",
      "PROCNAME",
      "PROCSEQN",
      "PROCSIZE",
      "PROCTYPE",
      "PROJID",
      "PTSCALE",
      "RA",
      "RADESYS",
      "RESTFRQ",
      "SCAN",
      "SCANFILE",
      "SIMPLE",
      "SIMULATE",
      "SKYFREQ",
      "SRCCNT",
      "SRCTYPE",
      "SUBMOTIN",
      "SUBNODLN",
      "SUBNUNIT",
      "SUBOFFSY",
      "SUBSTRTY",
      "SUBXT1",
      "SUBXT2",
      "SUBYT1",
      "SUBYT2",
      "SUBZT1",
      "SUBZT2",
      "SWSTATE",
      "SWTCHSIG",
      "TELESCOP",
      "TIMESYS",
      "TRADHOLO",
      "VELDEF",
      "VELOCITY",
      "ZERNSFC",
      "catalog_AKA",
      "catalog_BMAX",
      "catalog_BMIN",
      "catalog_DejaVu",
      "catalog_F1",
      "catalog_FILE",
      "catalog_INTENSITY",
      "catalog_LINE",
      "catalog_Line",
      "catalog_NAME",
      "catalog_NEDname",
      "catalog_NOBSQ",
      "catalog_NOBSX",
      "catalog_NVSS",
      "catalog_OFFSET",
      "catalog_P",
      "catalog_RESTFREQ",
      "catalog_Rgal",
      "catalog_S0_7",
      "catalog_S1400",
      "catalog_S15",
      "catalog_S1_3",
      "catalog_S2",
      "catalog_S20",
      "catalog_S22235",
      "catalog_S3_3",
      "catalog_S3_5",
      "catalog_S400",
      "catalog_S6",
      "catalog_SZMAX",
      "catalog_SZMIN",
      "catalog_TCJ",
      "catalog_USERADVEL",
      "catalog_VEL",
      "catalog_VELOCITY",
      "catalog_Velocity",
      "catalog_alias",
      "catalog_angsize",
      "catalog_b",
      "catalog_binary",
      "catalog_bname",
      "catalog_bsc_efact",
      "catalog_bsize",
      "catalog_color",
      "catalog_coordinates",
      "catalog_coordname",
      "catalog_dec_deg",
      "catalog_decoffset",
      "catalog_decsize",
      "catalog_dm",
      "catalog_e95_amin",
      "catalog_found_by",
      "catalog_itime",
      "catalog_jname",
      "catalog_l",
      "catalog_location",
      "catalog_lsize",
      "catalog_myraoff",
      "catalog_offDec",
      "catalog_parfile",
      "catalog_pk",
      "catalog_ra_deg",
      "catalog_region",
      "catalog_restframe",
      "catalog_restfreq",
      "catalog_source",
      "catalog_start_lst",
      "catalog_status",
      "catalog_t",
      "catalog_vel",
      "catalog_veldef",
      "catalog_velocity",
      "catalog_velocitydefinition",
      "catalog_z",
      "config_",
      "config_CCO",
      "config_CCS",
      "config_H2O",
      "config_HC11N_23",
      "config_HC11N_24",
      "config_HC11N_25",
      "config_HC11N_26",
      "config_HC11N_27",
      "config_HC11N_28",
      "config_HC11N_29",
      "config_HC11N_37",
      "config_HC11N_38",
      "config_HC11N_39",
      "config_HC11and7N",
      "config_HC13N_59",
      "config_HC13N_60",
      "config_HC13N_61",
      "config_HC13N_62",
      "config_HC13N_63",
      "config_HC3N_0",
      "config_HC5N_2",
      "config_HC7NJ19",
      "config_HC7N_11",
      "config_HC7N_7",
      "config_HC7N_8",
      "config_HC9NJ37",
      "config_HC9NJ38",
      "config_HC9N_13",
      "config_HC9N_14",
      "config_HC9N_15",
      "config_HC9N_16",
      "config_HC9N_22",
      "config_HDO",
      "config_NH3J42",
      "config_NH3J54",
      "config_backend",
      "config_bandwidth",
      "config_bcpm_ch_bw",
      "config_bcpm_hardware",
      "config_bcpm_sample_time",
      "config_bcpm_source_name",
      "config_bcpm_submanager",
      "config_bcpm_sum_pol",
      "config_beam",
      "config_beamswitch",
      "config_cal",
      "config_ccb_XL_on_integs",
      "config_ccb_YR_on_integs",
      "config_ccb_both_on_integs",
      "config_ccb_bswfreq",
      "config_ccb_cal_off_integs",
      "config_deltafreq",
      "config_guppi_datadisk",
      "config_guppi_fold_bins",
      "config_guppi_fold_dumptime",
      "config_guppi_fold_parfile",
      "config_guppi_numchan",
      "config_guppi_obsmode",
      "config_guppi_outbits",
      "config_guppi_parfile",
      "config_guppi_polnmode",
      "config_guppi_scale",
      "config_holo_refatten",
      "config_holo_reqinteg",
      "config_holo_testatten",
      "config_if3freq",
      "config_ifbw",
      "config_iftarget",
      "config_lo2freq",
      "config_mustang_defaultdac",
      "config_mustang_init",
      "config_mustang_lsync",
      "config_mustang_lutstart",
      "config_mustang_nsamp",
      "config_mustang_nstep",
      "config_mustang_settle",
      "config_mustang_tuning",
      "config_nchan",
      "config_nfeeds",
      "config_noisecal",
      "config_notchfilter",
      "config_nwin",
      "config_obsmode",
      "config_obstype",
      "config_pol",
      "config_polarization",
      "config_polswitch",
      "config_receiver",
      "config_restfreq",
      "config_smode",
      "config_sp_mode",
      "config_sp_polyco",
      "config_spect_crosspol",
      "config_spect_levels",
      "config_spect_numbanks",
      "config_swfreq",
      "config_swmode",
      "config_swper",
      "config_swtype",
      "config_tint",
      "config_vdef",
      "config_vframe",
      "config_vhigh",
      "config_vlbi_phasecal",
      "config_vlow",
      "config_vnoisecal",
      "config_xfer",
    ],
    :labels => {
      "keys" => "keys",
      "AZ" => "AZ",
      "BITPIX" => "BITPIX",
      "BLOCK" => "BLOCK",
      "CALTAG" => "CALTAG",
      "COMMENT" => "COMMENT",
      "COORDSYS" => "COORDSYS",
      "DATE-OBS" => "DATE-OBS",
      "DATEBLD" => "DATEBLD",
      "DEC" => "DEC",
      "DIODE" => "DIODE",
      "EL" => "EL",
      "EQUINOX" => "EQUINOX",
      "EXTEND" => "EXTEND",
      "FITSVER" => "FITSVER",
      "GBTMCVER" => "GBTMCVER",
      "GLAT" => "GLAT",
      "GLON" => "GLON",
      "HA" => "HA",
      "HALFPOW" => "HALFPOW",
      "INSTRUME" => "INSTRUME",
      "KADRIFT" => "KADRIFT",
      "LASTOFF" => "LASTOFF",
      "LASTON" => "LASTON",
      "LEDTEST" => "LEDTEST",
      "NAXIS" => "NAXIS",
      "OBJECT" => "OBJECT",
      "OBSERVER" => "OBSERVER",
      "OBSID" => "OBSID",
      "OBSTAG" => "OBSTAG",
      "OBSTYPE" => "OBSTYPE",
      "OOFDZ" => "OOFDZ",
      "ORIGIN" => "ORIGIN",
      "PROCNAME" => "PROCNAME",
      "PROCSEQN" => "PROCSEQN",
      "PROCSIZE" => "PROCSIZE",
      "PROCTYPE" => "PROCTYPE",
      "PROJID" => "PROJID",
      "PTSCALE" => "PTSCALE",
      "RA" => "RA",
      "RADESYS" => "RADESYS",
      "RESTFRQ" => "RESTFRQ",
      "SCAN" => "SCAN",
      "SCANFILE" => "SCANFILE",
      "SIMPLE" => "SIMPLE",
      "SIMULATE" => "SIMULATE",
      "SKYFREQ" => "SKYFREQ",
      "SRCCNT" => "SRCCNT",
      "SRCTYPE" => "SRCTYPE",
      "SUBMOTIN" => "SUBMOTIN",
      "SUBNODLN" => "SUBNODLN",
      "SUBNUNIT" => "SUBNUNIT",
      "SUBOFFSY" => "SUBOFFSY",
      "SUBSTRTY" => "SUBSTRTY",
      "SUBXT1" => "SUBXT1",
      "SUBXT2" => "SUBXT2",
      "SUBYT1" => "SUBYT1",
      "SUBYT2" => "SUBYT2",
      "SUBZT1" => "SUBZT1",
      "SUBZT2" => "SUBZT2",
      "SWSTATE" => "SWSTATE",
      "SWTCHSIG" => "SWTCHSIG",
      "TELESCOP" => "TELESCOP",
      "TIMESYS" => "TIMESYS",
      "TRADHOLO" => "TRADHOLO",
      "VELDEF" => "VELDEF",
      "VELOCITY" => "VELOCITY",
      "ZERNSFC" => "ZERNSFC",
      "catalog_AKA" => "catalog_AKA",
      "catalog_BMAX" => "catalog_BMAX",
      "catalog_BMIN" => "catalog_BMIN",
      "catalog_DejaVu" => "catalog_DejaVu",
      "catalog_F1" => "catalog_F1",
      "catalog_FILE" => "catalog_FILE",
      "catalog_INTENSITY" => "catalog_INTENSITY",
      "catalog_LINE" => "catalog_LINE",
      "catalog_Line" => "catalog_Line",
      "catalog_NAME" => "catalog_NAME",
      "catalog_NEDname" => "catalog_NEDname",
      "catalog_NOBSQ" => "catalog_NOBSQ",
      "catalog_NOBSX" => "catalog_NOBSX",
      "catalog_NVSS" => "catalog_NVSS",
      "catalog_OFFSET" => "catalog_OFFSET",
      "catalog_P" => "catalog_P",
      "catalog_RESTFREQ" => "catalog_RESTFREQ",
      "catalog_Rgal" => "catalog_Rgal",
      "catalog_S0_7" => "catalog_S0_7",
      "catalog_S1400" => "catalog_S1400",
      "catalog_S15" => "catalog_S15",
      "catalog_S1_3" => "catalog_S1_3",
      "catalog_S2" => "catalog_S2",
      "catalog_S20" => "catalog_S20",
      "catalog_S22235" => "catalog_S22235",
      "catalog_S3_3" => "catalog_S3_3",
      "catalog_S3_5" => "catalog_S3_5",
      "catalog_S400" => "catalog_S400",
      "catalog_S6" => "catalog_S6",
      "catalog_SZMAX" => "catalog_SZMAX",
      "catalog_SZMIN" => "catalog_SZMIN",
      "catalog_TCJ" => "catalog_TCJ",
      "catalog_USERADVEL" => "catalog_USERADVEL",
      "catalog_VEL" => "catalog_VEL",
      "catalog_VELOCITY" => "catalog_VELOCITY",
      "catalog_Velocity" => "catalog_Velocity",
      "catalog_alias" => "catalog_alias",
      "catalog_angsize" => "catalog_angsize",
      "catalog_b" => "catalog_b",
      "catalog_binary" => "catalog_binary",
      "catalog_bname" => "catalog_bname",
      "catalog_bsc_efact" => "catalog_bsc_efact",
      "catalog_bsize" => "catalog_bsize",
      "catalog_color" => "catalog_color",
      "catalog_coordinates" => "catalog_coordinates",
      "catalog_coordname" => "catalog_coordname",
      "catalog_dec_deg" => "catalog_dec_deg",
      "catalog_decoffset" => "catalog_decoffset",
      "catalog_decsize" => "catalog_decsize",
      "catalog_dm" => "catalog_dm",
      "catalog_e95_amin" => "catalog_e95_amin",
      "catalog_found_by" => "catalog_found_by",
      "catalog_itime" => "catalog_itime",
      "catalog_jname" => "catalog_jname",
      "catalog_l" => "catalog_l",
      "catalog_location" => "catalog_location",
      "catalog_lsize" => "catalog_lsize",
      "catalog_myraoff" => "catalog_myraoff",
      "catalog_offDec" => "catalog_offDec",
      "catalog_parfile" => "catalog_parfile",
      "catalog_pk" => "catalog_pk",
      "catalog_ra_deg" => "catalog_ra_deg",
      "catalog_region" => "catalog_region",
      "catalog_restframe" => "catalog_restframe",
      "catalog_restfreq" => "catalog_restfreq",
      "catalog_source" => "catalog_source",
      "catalog_start_lst" => "catalog_start_lst",
      "catalog_status" => "catalog_status",
      "catalog_t" => "catalog_t",
      "catalog_vel" => "catalog_vel",
      "catalog_veldef" => "catalog_veldef",
      "catalog_velocity" => "catalog_velocity",
      "catalog_velocitydefinition" => "catalog_velocitydefinition",
      "catalog_z" => "catalog_z",
      "config_" => "config_",
      "config_CCO" => "config_CCO",
      "config_CCS" => "config_CCS",
      "config_H2O" => "config_H2O",
      "config_HC11N_23" => "config_HC11N_23",
      "config_HC11N_24" => "config_HC11N_24",
      "config_HC11N_25" => "config_HC11N_25",
      "config_HC11N_26" => "config_HC11N_26",
      "config_HC11N_27" => "config_HC11N_27",
      "config_HC11N_28" => "config_HC11N_28",
      "config_HC11N_29" => "config_HC11N_29",
      "config_HC11N_37" => "config_HC11N_37",
      "config_HC11N_38" => "config_HC11N_38",
      "config_HC11N_39" => "config_HC11N_39",
      "config_HC11and7N" => "config_HC11and7N",
      "config_HC13N_59" => "config_HC13N_59",
      "config_HC13N_60" => "config_HC13N_60",
      "config_HC13N_61" => "config_HC13N_61",
      "config_HC13N_62" => "config_HC13N_62",
      "config_HC13N_63" => "config_HC13N_63",
      "config_HC3N_0" => "config_HC3N_0",
      "config_HC5N_2" => "config_HC5N_2",
      "config_HC7NJ19" => "config_HC7NJ19",
      "config_HC7N_11" => "config_HC7N_11",
      "config_HC7N_7" => "config_HC7N_7",
      "config_HC7N_8" => "config_HC7N_8",
      "config_HC9NJ37" => "config_HC9NJ37",
      "config_HC9NJ38" => "config_HC9NJ38",
      "config_HC9N_13" => "config_HC9N_13",
      "config_HC9N_14" => "config_HC9N_14",
      "config_HC9N_15" => "config_HC9N_15",
      "config_HC9N_16" => "config_HC9N_16",
      "config_HC9N_22" => "config_HC9N_22",
      "config_HDO" => "config_HDO",
      "config_NH3J42" => "config_NH3J42",
      "config_NH3J54" => "config_NH3J54",
      "config_backend" => "config_backend",
      "config_bandwidth" => "config_bandwidth",
      "config_bcpm_ch_bw" => "config_bcpm_ch_bw",
      "config_bcpm_hardware" => "config_bcpm_hardware",
      "config_bcpm_sample_time" => "config_bcpm_sample_time",
      "config_bcpm_source_name" => "config_bcpm_source_name",
      "config_bcpm_submanager" => "config_bcpm_submanager",
      "config_bcpm_sum_pol" => "config_bcpm_sum_pol",
      "config_beam" => "config_beam",
      "config_beamswitch" => "config_beamswitch",
      "config_cal" => "config_cal",
      "config_ccb_XL_on_integs" => "config_ccb_XL_on_integs",
      "config_ccb_YR_on_integs" => "config_ccb_YR_on_integs",
      "config_ccb_both_on_integs" => "config_ccb_both_on_integs",
      "config_ccb_bswfreq" => "config_ccb_bswfreq",
      "config_ccb_cal_off_integs" => "config_ccb_cal_off_integs",
      "config_deltafreq" => "config_deltafreq",
      "config_guppi_datadisk" => "config_guppi_datadisk",
      "config_guppi_fold_bins" => "config_guppi_fold_bins",
      "config_guppi_fold_dumptime" => "config_guppi_fold_dumptime",
      "config_guppi_fold_parfile" => "config_guppi_fold_parfile",
      "config_guppi_numchan" => "config_guppi_numchan",
      "config_guppi_obsmode" => "config_guppi_obsmode",
      "config_guppi_outbits" => "config_guppi_outbits",
      "config_guppi_parfile" => "config_guppi_parfile",
      "config_guppi_polnmode" => "config_guppi_polnmode",
      "config_guppi_scale" => "config_guppi_scale",
      "config_holo_refatten" => "config_holo_refatten",
      "config_holo_reqinteg" => "config_holo_reqinteg",
      "config_holo_testatten" => "config_holo_testatten",
      "config_if3freq" => "config_if3freq",
      "config_ifbw" => "config_ifbw",
      "config_iftarget" => "config_iftarget",
      "config_lo2freq" => "config_lo2freq",
      "config_mustang_defaultdac" => "config_mustang_defaultdac",
      "config_mustang_init" => "config_mustang_init",
      "config_mustang_lsync" => "config_mustang_lsync",
      "config_mustang_lutstart" => "config_mustang_lutstart",
      "config_mustang_nsamp" => "config_mustang_nsamp",
      "config_mustang_nstep" => "config_mustang_nstep",
      "config_mustang_settle" => "config_mustang_settle",
      "config_mustang_tuning" => "config_mustang_tuning",
      "config_nchan" => "config_nchan",
      "config_nfeeds" => "config_nfeeds",
      "config_noisecal" => "config_noisecal",
      "config_notchfilter" => "config_notchfilter",
      "config_nwin" => "config_nwin",
      "config_obsmode" => "config_obsmode",
      "config_obstype" => "config_obstype",
      "config_pol" => "config_pol",
      "config_polarization" => "config_polarization",
      "config_polswitch" => "config_polswitch",
      "config_receiver" => "config_receiver",
      "config_restfreq" => "config_restfreq",
      "config_smode" => "config_smode",
      "config_sp_mode" => "config_sp_mode",
      "config_sp_polyco" => "config_sp_polyco",
      "config_spect_crosspol" => "config_spect_crosspol",
      "config_spect_levels" => "config_spect_levels",
      "config_spect_numbanks" => "config_spect_numbanks",
      "config_swfreq" => "config_swfreq",
      "config_swmode" => "config_swmode",
      "config_swper" => "config_swper",
      "config_swtype" => "config_swtype",
      "config_tint" => "config_tint",
      "config_vdef" => "config_vdef",
      "config_vframe" => "config_vframe",
      "config_vhigh" => "config_vhigh",
      "config_vlbi_phasecal" => "config_vlbi_phasecal",
      "config_vlow" => "config_vlow",
      "config_vnoisecal" => "config_vnoisecal",
      "config_xfer" => "config_xfer",
    }
  }

  # "fielded" search select (pulldown)
  # label in pulldown is followed by the name of a SOLR request handler as
  # defined in solr/conf/solrconfig.xml
  config[:search_fields] ||= []
  config[:search_fields] << ['All Fields', 'search']
  # config[:search_fields] << ['Title', 'title_search']

  # "sort results by" select (pulldown)
  # label in pulldown is followed by the name of the SOLR field to sort by and
  # whether the sort is ascending or descending (it must be asc or desc
  # except in the relevancy case).
  # label is key, solr field is value
  config[:sort_fields] ||= []
  config[:sort_fields] << ['relevance', 'score desc, title_sort asc']

  # If there are more than this many search results, no spelling ("did you
  # mean") suggestion is offered.
  config[:spell_max] = 5
end

